services:
  - type: web
    name: vidhikpath
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vidhikpath.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13